server:
  port: 9094
spring:
  application:
    name: gateway-center
  cloud:
    gateway:
      #\u4EE3\u8868\u4ECE\u670D\u52A1\u6CE8\u518C\u4E2D\u5FC3\u83B7\u53D6\u5B9E\u4F8B\u5217\u8868
      discovery:
        locator:
          enabled: true
      routes:
      - id: service-consumer
        #lb\u8868\u793A\u4ECE\u6CE8\u518C\u4E2D\u5FC3\u83B7\u53D6\u670D\u52A1\u5B9E\u4F8B\uFF0Chttp\u8868\u793A\u7F51\u5740\u8F6C\u53D1
        uri: lb://service-consumer
        predicates:
        - Path=/service-consumer/**
        #\u5FC5\u987B\u5E26\u4E0Afilters StripPrefix\u622A\u53D6\u6389\u670D\u52A1\u540D\uFF0C\u5426\u5219\u8BBF\u95EE\u65F6\u4F1A\u5728\u8DEF\u5F84\u4E2D\u5E26\u4E0A\u670D\u52A1\u540D\uFF0C\u9020\u6210404
        filters:
        - StripPrefix=1
      - id: baidu
        uri: https://www.baidu.com
        predicates:
        - Path=/baidu
    consul:
      host: localhost
      port: 8500
      discovery:
        prefer-ip-address: true
        health-check-path: /health
        heartbeat:
          enabled: false