server:
  port: 9002

spring:
  application:
    name: zuul-center

#eureka配置
eureka:
  client:
    service-url:
      defaultZone: http://localhost:9000/eureka/

zuul:
  routes:
    service-consumer:
      path: /service-consumer/**
      serviceId: service-consumer