server:
  port: 9100
spring:
  application:
    name: service-consumer
  sleuth:
    sampler:
      probability: 1.0
    web:
      client:
        enabled: true
  zipkin:
    base-url: http://localhost:9003/
eureka:
  client:
    service-url:
      defaultZone: http://localhost:9000/eureka/
feign:
  hystrix:
    enabled: true

